### PR TITLE
Pypdf2 as alternative to Textract

### PR DESCRIPTION
**Pull request by devironl**
Hello Max
I have tried to propose an alternative to textract by using PyPdf2
Could you have a look on your Windows laptop ?
Thanks !

### CODE REVIEW

**Comment by madewild** [comment]
@devironl I have no access to my Windows system this week so that will have to wait...
I am not against it, but we will need textract in the last module anyway.

**Comment by madewild** [comment]
@DeLeb86 can you test this on Windows?
then we decide between textract and PyPDF2

**Comment by DeLeb86** [comment]
@madewild I tested pypdf2 on Windows. it works fine.
The documentation looks quite complete.

**Comment by madewild** [comment]
Ok but we still need textract in module6/s1_extraction.ipynb so don't remove it from requirements!

**Comment by DeLeb86** [comment]
ok. done :-)

**Pull request merged**
